### ISSUE TITLE
插件如何使用？

### ISSUE THREAD

**Issue by Hanx152** [synodriver/nonebot_plugin_picsearcher#19]
大佬，我@机器人然后搜图他说参数不正确，可是我也没看到别的使用说明啊

**Comment by synodriver** [comment]
@出来之后选择图源 再发图就是了

**Comment by Hanx152** [comment]
@之后打选择图源？

**Comment by synodriver** [comment]
@之后机器会问的

**Comment by Hanx152** [comment]
我的咋不问呢

**Comment by synodriver** [comment]
有截图吗我看看

**Comment by Hanx152** [comment]
现在有反应了，但搜图有这个报错
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_picsearcher\__init__.py", line 83, in get_setu
    [msg if isinstance(msg, Message) else Message(msg) async for msg in get_des(url, mod)])
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_picsearcher\__init__.py", line 83, in <listcomp>
    [msg if isinstance(msg, Message) else Message(msg) async for msg in get_des(url, mod)])
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_picsearcher\__init__.py", line 35, in get_des
    async for msg in get_des_ex(url):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_picsearcher\ex.py", line 99, in get_des
    image_data: List[Tuple] = await get_pic_from_url(url)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_picsearcher\ex.py", line 74, in get_pic_from_url
    async with session.post(target, data=data, headers=headers, proxy=proxy) as res:
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 535, in _request
    conn = await self._connector.connect(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 905, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1221, in _create_proxy_connection
    proxy_req = ClientRequest(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client_reqrep.py", line 305, in __init__
    self.update_host(url)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client_reqrep.py", line 366, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: #%20type:%20str%20e.g.

**Comment by synodriver** [comment]
你发的不是图吧……url错误？

**Comment by Hanx152** [comment]
不该啊，我从相册发的

**Comment by Aaisui** [comment]
这个大概是代理问题，没访问到超时报错了

**Comment by synodriver** [comment]
要不把图给我看看（

**Comment by daguazi** [comment]
Traceback (most recent call last):
  File "c:\users\呱子\appdata\local\programs\python\python38\lib\site-packages\aiohttp\connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "c:\users\呱子\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "c:\users\呱子\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "c:\users\呱子\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "c:\users\呱子\appdata\local\programs\python\python38\lib\asyncio\proactor_events.py", line 702, in sock_connect
    return await self._proactor.connect(sock, address)
  File "c:\users\呱子\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 812, in _poll
    value = callback(transferred, key, ov)
  File "c:\users\呱子\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 599, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\呱子\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_picsearcher\__init__.py", line 83, in get_setu
    [msg if isinstance(msg, Message) else Message(msg) async for msg in get_des(url, mod)])
  File "c:\users\呱子\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_picsearcher\__init__.py", line 83, in <listcomp>
    [msg if isinstance(msg, Message) else Message(msg) async for msg in get_des(url, mod)])
  File "c:\users\呱子\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_picsearcher\__init__.py", line 35, in get_des
    async for msg in get_des_ex(url):
  File "c:\users\呱子\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_picsearcher\ex.py", line 99, in get_des
    image_data: List[Tuple] = await get_pic_from_url(url)
  File "c:\users\呱子\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_picsearcher\ex.py", line 74, in get_pic_from_url
    async with session.post(target, data=data, headers=headers, proxy=proxy) as res:
  File "c:\users\呱子\appdata\local\programs\python\python38\lib\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "c:\users\呱子\appdata\local\programs\python\python38\lib\site-packages\aiohttp\client.py", line 535, in _request
    conn = await self._connector.connect(
  File "c:\users\呱子\appdata\local\programs\python\python38\lib\site-packages\aiohttp\connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "c:\users\呱子\appdata\local\programs\python\python38\lib\site-packages\aiohttp\connector.py", line 905, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "c:\users\呱子\appdata\local\programs\python\python38\lib\site-packages\aiohttp\connector.py", line 1231, in _create_proxy_connection
    transport, proto = await self._create_direct_connection(
  File "c:\users\呱子\appdata\local\programs\python\python38\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "c:\users\呱子\appdata\local\programs\python\python38\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "c:\users\呱子\appdata\local\programs\python\python38\lib\site-packages\aiohttp\connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientProxyConnectionError: Cannot connect to host 127.0.0.1:8889 ssl:default [远程计算机拒绝网络连接。]
我是这个报错

**Comment by synodriver** [comment]
你没加代理？得改成你的地址吧

**Comment by snakeuncle2** [comment]
大佬你好，我是纯小白一个，试着自己搭了一个bot和您的插件
dev的设置如下HOST=127.0.0.1
PORT=8080
SUPERUSERS=["512019302", "778688058"]
NICKNAME=["snake", "bot"] # 配置机器人的昵称
COMMAND_START=["/", ""] # 配置命令起始字符
COMMAND_SEP=["."] # 配置命令分割字符

Custom Configs
CUSTOM_CONFIG1="config in env file"
CUSTOM_CONFIG2= # 留空则从系统环境变量读取，如不存在则为空字符串
EX_COOKIE=XXXXX
PROXY=http://127.0.0.1:4780/ # type: str e.g. PROXY=http://127.0.0.1:8080/
SEARCH_LIMIT=2 # 搜索限制 防刷屏
RISK_CONTROL=true # 风控模式 启动后会使用合并转发 只有gocq有实现
RECORD_PRIORITY=99 # 记录上一张图片matcher的优先级，与 上一张 命令有关

然后是错误参数
Traceback (most recent call last):
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 969, in _wrap_create_connection
return await self._loop.create_connection(*args, **kwargs) # type: ignore # noqa
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1089, in create_connection
transport, protocol = await self._create_connection_transport(
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1119, in _create_connection_transport
await waiter
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 397, in _loop_writing
self._write_fut = self._loop._proactor.send(self._sock, data)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 534, in send
self._register_with_iocp(conn)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 723, in _register_with_iocp
_overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 87] 参数错误。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_picsearcher_init_.py", line 83, in get_setu
[msg if isinstance(msg, Message) else Message(msg) async for msg in get_des(url, mod)])
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_picsearcher_init_.py", line 83, in
[msg if isinstance(msg, Message) else Message(msg) async for msg in get_des(url, mod)])
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_picsearcher_init_.py", line 47, in get_des
async for msg in get_des_sau(url):
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_picsearcher\saucenao.py", line 84, in get_des
image_data: List[Tuple] = await get_pic_from_url(url)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_picsearcher\saucenao.py", line 77, in get_pic_from_url
async with session.post("https://saucenao.com/search.php", data=data, headers=header, proxy=proxy) as res:
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1117, in aenter
self._resp = await self._coro
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 520, in _request
conn = await self._connector.connect(
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 535, in connect
proto = await self._create_connection(req, traces, timeout)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 890, in _create_connection
_, proto = await self._create_proxy_connection(req, traces, timeout)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1139, in _create_proxy_connection
transport, proto = await self._wrap_create_connection(
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 975, in _wrap_create_connection
raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host saucenao.com:443 ssl:default [参数错误。]

我按照您的步骤和上网查找了问题，发现不知道如何解决，麻烦请您帮看一下，谢谢

**Comment by synodriver** [comment]
你这个真的有设置代理吗？没代理就不用写那个proxy

**Comment by snakeuncle2** [comment]
> 你这个真的有设置代理吗？没代理就不用写那个代理

谢谢！我好像知道问题在哪了！

**Comment by daguazi** [comment]
谢谢大佬，是我代理的问题
