### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Winj1e** [synodriver/nonebot_plugin_picsearcher#21]
![image](https://user-images.githubusercontent.com/105339518/168764768-59ddc726-90ab-436f-99ae-b277f67b19b3.png)
![L)JFT8)_TF4XLMP%29ZO1M3](https://user-images.githubusercontent.com/105339518/168764822-fd4e23fa-ee9f-4a8a-8198-419c8b95e390.png)
![FJ6AE{ZE%FTVIN3{Z5VDE~3](https://user-images.githubusercontent.com/105339518/168764838-214a0f29-5a4a-4dc0-9466-ea35a70996e1.png)
请问大佬代码没报错为什么这里会报错啊
![image](https://user-images.githubusercontent.com/105339518/168765577-30e3b159-e249-42de-9cf2-5871dbda1514.png)
这个是报错信息
Traceback (most recent call last):
  File "C:\Users\wdnmd_10108523518376\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_picsearcher\__init__.py", line 83, in get_setu
    [msg if isinstance(msg, Message) else Message(msg) async for msg in get_des(url, mod)])
  File "C:\Users\wdnmd_10108523518376\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_picsearcher\__init__.py", line 83, in <listcomp>
    [msg if isinstance(msg, Message) else Message(msg) async for msg in get_des(url, mod)])
  File "C:\Users\wdnmd_10108523518376\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_picsearcher\__init__.py", line 35, in get_des
    async for msg in get_des_ex(url):
  File "C:\Users\wdnmd_10108523518376\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_picsearcher\ex.py", line 99, in get_des
    image_data: List[Tuple] = await get_pic_from_url(url)
  File "C:\Users\wdnmd_10108523518376\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_picsearcher\ex.py", line 74, in get_pic_from_url
    async with session.post(target, data=data, headers=headers, proxy=proxy) as res:
  File "C:\Users\wdnmd_10108523518376\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "C:\Users\wdnmd_10108523518376\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 535, in _request
    conn = await self._connector.connect(
  File "C:\Users\wdnmd_10108523518376\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\wdnmd_10108523518376\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 905, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "C:\Users\wdnmd_10108523518376\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1221, in _create_proxy_connection
    proxy_req = ClientRequest(
  File "C:\Users\wdnmd_10108523518376\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client_reqrep.py", line 305, in __init__
    self.update_host(url)
  File "C:\Users\wdnmd_10108523518376\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client_reqrep.py", line 366, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: XXXX

**Comment by qwe1187292926** [comment]
网络问题，ex需要设置代理

**Comment by Winj1e** [comment]
其他的也是这样

**Comment by synodriver** [comment]
代理问题，最好用外国的机器

**Comment by Winj1e** [comment]
行吧，感谢解答

**Comment by synodriver** [comment]
最近似乎类似的网络问题原来越多了，那几个还能用的源也是时不时抽风……
