### ISSUE TITLE
搜图机器人报参数错误

### ISSUE THREAD

**Issue by Arturia169** [synodriver/nonebot_plugin_picsearcher#25]
报错如下

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_picsearcher/__init__.py", line 83, in get_setu
    [msg if isinstance(msg, Message) else Message(msg) async for msg in get_des(url, mod)])
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_picsearcher/__init__.py", line 83, in <listcomp>
    [msg if isinstance(msg, Message) else Message(msg) async for msg in get_des(url, mod)])
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_picsearcher/__init__.py", line 35, in get_des
    async for msg in get_des_ex(url):
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_picsearcher/ex.py", line 99, in get_des
    image_data: List[Tuple] = await get_pic_from_url(url)
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_picsearcher/ex.py", line 74, in get_pic_from_url
    async with session.post(target, data=data, headers=headers, proxy=proxy) as res:
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 905, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 1221, in _create_proxy_connection
    proxy_req = ClientRequest(
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 305, in __init__
    self.update_host(url)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 366, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: XXXX

**Comment by synodriver** [comment]
代理问题，如果没代理可以不用写
