### ISSUE TITLE
无法加载插件

### ISSUE THREAD

**Issue by JuuiceP** [synodriver/nonebot_plugin_picsearcher#26]
如题，pip安装后提示找不到插件？

05-20 17:25:17 [SUCCESS] nonebot | Succeeded to import "nonebot.plugins.echo"
05-20 17:25:17 [ERROR] nonebot | Failed to import "nonebot_plugin_picsearcher"
Traceback (most recent call last):
  File "c:\program files\python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\python\Scripts\nb.exe\__main__.py", line 7, in <module>

    sys.exit(main())
  File "c:\program files\python\lib\site-packages\click\core.py", line 1130, in
__call__
    return self.main(*args, **kwargs)
  File "c:\program files\python\lib\site-packages\click\core.py", line 1055, in
main
    rv = self.invoke(ctx)
  File "c:\program files\python\lib\site-packages\click\core.py", line 1657, in
invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\program files\python\lib\site-packages\click\core.py", line 1404, in
invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\python\lib\site-packages\click\core.py", line 760, in i
nvoke
    return __callback(*args, **kwargs)
  File "c:\program files\python\lib\site-packages\nb_cli\commands\main.py", line
 30, in run
    run_bot(file, app)
  File "c:\program files\python\lib\site-packages\nb_cli\handlers\deploy.py", li
ne 19, in run_bot
    module = importlib.import_module(module_name)
  File "c:\program files\python\lib\importlib\__init__.py", line 127, in import_
module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\bot.py", line 27, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "c:\program files\python\lib\site-packages\nonebot\plugin\load.py", line
119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "c:\program files\python\lib\site-packages\nonebot\plugin\load.py", line
53, in load_all_plugins
    return manager.load_all_plugins()
  File "c:\program files\python\lib\site-packages\nonebot\plugin\manager.py", li
ne 128, in load_all_plugins
    return set(
  File "c:\program files\python\lib\site-packages\nonebot\plugin\manager.py", li
ne 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
> File "c:\program files\python\lib\site-packages\nonebot\plugin\manager.py", li
ne 104, in load_plugin
    module = importlib.import_module(name)
  File "c:\program files\python\lib\importlib\__init__.py", line 127, in import_
module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\program files\python\lib\site-packages\nonebot\plugin\manager.py", li
ne 194, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\program files\python\lib\site-packages\nonebot_plugin_picsearcher\__i
nit__.py", line 15, in <module>
    from .ex import get_des as get_des_ex
  File "c:\program files\python\lib\site-packages\nonebot_plugin_picsearcher\ex.
py", line 15, in <module>
    cookie: str = driver.config.ex_cookie
AttributeError: 'Config' object has no attribute 'ex_cookie'
05-20 17:25:17 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apschedul
er"
05-20 17:25:17 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_setu_now"

05-20 17:25:17 [SUCCESS] nonebot | Running NoneBot...
05-20 17:25:17 [DEBUG] nonebot | Loaded adapters: OneBot V11
05-20 17:25:17 [INFO] uvicorn | Will watch for changes in these directories: ['C
:\\Users\\Administrator\\Desktop\\Kokoro']
05-20 17:25:17 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8080 (Press
CTRL+C to quit)
05-20 17:25:17 [INFO] uvicorn | Started reloader process [8500] using watchgod
05-20 17:25:18 [WARNING] uvicorn | The --reload flag should not be used in produ
ction on Windows.
05-20 17:25:18 [SUCCESS] nonebot | NoneBot is initializing...
05-20 17:25:18 [INFO] nonebot | Current Env: dev
05-20 17:25:18 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': I
Pv4Address('127.0.0.1'), 'port': 8080, 'log_level': 'DEBUG', 'api_timeout': 30.0
, 'superusers': {'1354961639'}, 'nickname': {'可可萝'}, 'command_start': {'/'},
'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120),
 'search_limit': 2, 'risk_control': True, 'record_priority': 99, 'fastapi_reload
': True, 'environment': 'dev'}
05-20 17:25:18 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
05-20 17:25:18 [SUCCESS] nonebot | Succeeded to import "nonebot.plugins.echo"
05-20 17:25:18 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apschedul
er"
05-20 17:25:18 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_setu_now"

05-20 17:25:18 [ERROR] nonebot | Failed to import "nonebot_plugin_picsearcher"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\program files\python\lib\multiprocessing\spawn.py", line 116, in spaw
n_main
    exitcode = _main(fd, parent_sentinel)
  File "c:\program files\python\lib\multiprocessing\spawn.py", line 129, in _mai
n
    return self._bootstrap(parent_sentinel)
  File "c:\program files\python\lib\multiprocessing\process.py", line 315, in _b
ootstrap
    self.run()
  File "c:\program files\python\lib\multiprocessing\process.py", line 108, in ru
n
    self._target(*self._args, **self._kwargs)
  File "c:\program files\python\lib\site-packages\uvicorn\subprocess.py", line 7
6, in subprocess_started
    target(sockets=sockets)
  File "c:\program files\python\lib\site-packages\uvicorn\server.py", line 60, i
n run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\program files\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\program files\python\lib\asyncio\base_events.py", line 603, in run_un
til_complete
    self.run_forever()
  File "c:\program files\python\lib\asyncio\base_events.py", line 570, in run_fo
rever
    self._run_once()
  File "c:\program files\python\lib\asyncio\base_events.py", line 1859, in _run_
once
    handle._run()
  File "c:\program files\python\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "c:\program files\python\lib\site-packages\uvicorn\server.py", line 67, i
n serve
    config.load()
  File "c:\program files\python\lib\site-packages\uvicorn\config.py", line 458,
in load
    self.loaded_app = import_from_string(self.app)
  File "c:\program files\python\lib\site-packages\uvicorn\importer.py", line 21,
 in import_from_string
    module = importlib.import_module(module_str)
  File "c:\program files\python\lib\importlib\__init__.py", line 127, in import_
module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\bot.py", line 27, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "c:\program files\python\lib\site-packages\nonebot\plugin\load.py", line
119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "c:\program files\python\lib\site-packages\nonebot\plugin\load.py", line
53, in load_all_plugins
    return manager.load_all_plugins()
  File "c:\program files\python\lib\site-packages\nonebot\plugin\manager.py", li
ne 128, in load_all_plugins
    return set(
  File "c:\program files\python\lib\site-packages\nonebot\plugin\manager.py", li
ne 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
> File "c:\program files\python\lib\site-packages\nonebot\plugin\manager.py", li
ne 104, in load_plugin
    module = importlib.import_module(name)
  File "c:\program files\python\lib\importlib\__init__.py", line 127, in import_
module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\program files\python\lib\site-packages\nonebot\plugin\manager.py", li
ne 194, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\program files\python\lib\site-packages\nonebot_plugin_picsearcher\__i
nit__.py", line 15, in <module>
    from .ex import get_des as get_des_ex
  File "c:\program files\python\lib\site-packages\nonebot_plugin_picsearcher\ex.
py", line 15, in <module>
    cookie: str = driver.config.ex_cookie
AttributeError: 'Config' object has no attribute 'ex_cookie'
05-20 17:25:18 [INFO] uvicorn | Started server process [4104]
05-20 17:25:18 [INFO] uvicorn | Waiting for application startup.
05-20 17:25:18 [INFO] nonebot_plugin_apscheduler | Scheduler Started
05-20 17:25:18 [INFO] uvicorn | Application startup complete.
05-20 17:25:19 [INFO] uvicorn | ('127.0.0.1', 59364) - "WebSocket /onebot/v11/ws
/" [accepted]

**Comment by synodriver** [comment]
你安装的什么版本？

**Comment by JuuiceP** [comment]
nonebot2 使用pip install nonebot-plugin-picsearcher==0.1.6rc2命令安装的

**Comment by synodriver** [comment]
我的锅（忘了更新readme了）直接pip install -U nonebot-plugin-picsearcher更新下

**Comment by JuuiceP** [comment]
成功了，谢谢大佬
