### ISSUE TITLE
搜图用ex报错乱码，开了香港代理全局模式

### ISSUE THREAD

**Issue by nertcy** [synodriver/nonebot_plugin_picsearcher#30]
1、是不知道ex_cookie=后面填什么

![image](https://user-images.githubusercontent.com/94539226/169675324-8ecae010-cd8d-4926-a5cd-6107d6fb1b65.png)
易北. bot 10:07:26
参数错误

易北. bot 10:07:26
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-C596GTka-py3.8\lib\site-packages\aiohttp\connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\zhenxun_bot-0.1.5.3\my_plugins\picsearcher\__init__.py", line 86, in get_setu
    [msg if isinstance(msg, Message) else Message(msg) async for msg in get_des(url, mod)])
  File "C:\Program Files\zhenxun_bot-0.1.5.3\my_plugins\picsearcher\__init__.py", line 86, in <listcomp>
    [msg if isinstance(msg, Message) else Message(msg) async for msg in get_des(url, mod)])
  File "C:\Program Files\zhenxun_bot-0.1.5.3\my_plugins\picsearcher\__init__.py", line 38, in get_des
    async for msg in get_des_ex(url):
  File "C:\Program Files\zhenxun_bot-0.1.5.3\my_plugins\picsearcher\ex.py", line 99, in get_des
    image_data: List[Tuple] = await get_pic_from_url(url)
  File "C:\Program Files\zhenxun_bot-0.1.5.3\my_plugins\picsearcher\ex.py", line 74, in get_pic_from_url
    async with session.post(target, data=data, headers=headers, proxy=proxy) as res:
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-C596GTka-py3.8\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-C596GTka-py3.8\lib\site-packages\aiohttp\client.py", line 520, in _request
    conn = await self._connector.connect(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-C596GTka-py3.8\lib\site-packages\aiohttp\connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-C596GTka-py3.8\lib\site-packages\aiohttp\connector.py", line 890, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-C596GTka-py3.8\lib\site-packages\aiohttp\connector.py", line 1139, in _create_proxy_connection
    transport, proto = await self._wrap_create_connection(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-C596GTka-py3.8\lib\site-packages\aiohttp\connector.py", line 971, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host upld.e-hentai.org:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')]

**Comment by synodriver** [comment]
aiohttp不能使用https代理，这是一个python的一个已知的历史悠久的bug，ex_cookie是从浏览器里面进入ex站之后f12扣下来的，aiohttp的ssl报错可以尝试使用ssl=False忽略之

**Comment by nertcy** [comment]
> aiohttp不能使用https代理，这是一个python的一个已知的历史悠久的bug，ex_cookie是从浏览器里面进入ex站之后f12扣下来的，aiohttp的ssl报错可以尝试使用ssl=False忽略之

谢谢，cookie我已经在ipd_pass_hash找到了，但是看你留言说如果是e-H不需要cookie也是在报错，有没有什么有效的解决方法呢？aiohttp的ssl报错我不太明白应该如何修改。可否举个例子（不是很懂Python代码）

**Comment by nertcy** [comment]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-C596GTka-py3.8\lib\site-packages\aiohttp\connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\zhenxun_bot-0.1.5.3\my_plugins\picsearcher\__init__.py", line 82, in get_setu
    async for msg in limiter(get_des(url, mod), getattr(bot.config, "search_limit", None) or 2):
  File "C:\Program Files\zhenxun_bot-0.1.5.3\my_plugins\picsearcher\utils.py", line 9, in limiter
    yield await gen.asend(None)
  File "C:\Program Files\zhenxun_bot-0.1.5.3\my_plugins\picsearcher\__init__.py", line 38, in get_des
    async for msg in get_des_ex(url):
  File "C:\Program Files\zhenxun_bot-0.1.5.3\my_plugins\picsearcher\ex.py", line 98, in get_des
    image_data: List[Tuple] = await get_pic_from_url(url)
  File "C:\Program Files\zhenxun_bot-0.1.5.3\my_plugins\picsearcher\ex.py", line 73, in get_pic_from_url
    async with session.post(target, data=data, headers=headers, proxy=proxy) as res:
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-C596GTka-py3.8\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-C596GTka-py3.8\lib\site-packages\aiohttp\client.py", line 520, in _request
    conn = await self._connector.connect(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-C596GTka-py3.8\lib\site-packages\aiohttp\connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-C596GTka-py3.8\lib\site-packages\aiohttp\connector.py", line 890, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-C596GTka-py3.8\lib\site-packages\aiohttp\connector.py", line 1139, in _create_proxy_connection
    transport, proto = await self._wrap_create_connection(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-C596GTka-py3.8\lib\site-packages\aiohttp\connector.py", line 971, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host exhentai.org:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')]

**Comment by nertcy** [comment]
> aiohttp不能使用https代理，这是一个python的一个已知的历史悠久的bug，ex_cookie是从浏览器里面进入ex站之后f12扣下来的，aiohttp的ssl报错可以尝试使用ssl=False忽略之
![` (NI`JK1V(K(H2VVQPV6DX](https://user-images.githubusercontent.com/94539226/169681901-d516f743-fe95-45ee-af5e-8707adeaa39a.png)
![FV%%UJGFN4 GE(6RIIZF$QV](https://user-images.githubusercontent.com/94539226/169681908-7be77d15-91f6-4aea-9cb0-cdacddd09535.jpg)
我没考虑ex的eh的就够啦，是这个eooki吗？还是看见有4个
![image](https://user-images.githubusercontent.com/94539226/169681932-58dfd57d-3089-4336-bb7d-67e27b66feca.png)

**Comment by synodriver** [comment]
eh的不用设置cookie

**Comment by nertcy** [comment]
> eh的不用设置cookie

已经尝试过不添加cookie还是在报错
![image](https://user-images.githubusercontent.com/94539226/169682183-f0f8adb9-64dd-4ec8-b40b-17e1fbe1f951.png)

**Comment by synodriver** [comment]
ssl问题……因为有些~~数据删除~~干扰了ssl握手

**Comment by synodriver** [comment]
可以用ssl=False忽略之

**Comment by nertcy** [comment]
> ssl问题……因为有些~数据删除~干扰了ssl握手

主要是不明白应该在那个py里面那条命令改，

**Comment by nertcy** [comment]
> 可以用ssl=False忽略之

![image](https://user-images.githubusercontent.com/94539226/169682553-b6333693-04fb-40ab-8846-1c18b6c981ae.png)
这样吗

**Comment by synodriver** [comment]
得改代码……但是这个奇怪的是有的vps不能改有的得改，似乎和区域有关，所以我也不太好直接禁用了ssl

**Comment by synodriver** [comment]
等下我加个选项吧，这个问题似乎挺普遍的

**Comment by nertcy** [comment]
> 等下我加个选项吧，这个问题似乎挺普遍的

好的麻烦了，大佬，我用的真寻的bot，都不能直接用pip上依赖只能在根目录建my_plugins来启用。也麻烦大佬这么有耐心的帮我。给你点个赞。我在env下面写了ssl=False忽律之后，刚刚试了一下，可以找一部分了。等待后续升级。

**Comment by LumiDust** [comment]
你好，请问我用ex图源搜索后报错是否为类似原因
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1091, in _start_tls_connection
    tls_transport = await self._loop.start_tls(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1240, in start_tls
    await waiter
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 945, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_picsearcher\__init__.py", line 86, in get_setu
    msgs = [msg if isinstance(msg, Message) else Message(msg) async for msg in get_des(url, mod)]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_picsearcher\__init__.py", line 86, in <listcomp>
    msgs = [msg if isinstance(msg, Message) else Message(msg) async for msg in get_des(url, mod)]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_picsearcher\__init__.py", line 39, in get_des
    async for msg in get_des_ex(url):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_picsearcher\ex.py", line 99, in get_des
    image_data: List[Tuple] = await get_pic_from_url(url)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_picsearcher\ex.py", line 74, in get_pic_from_url
    async with session.post(target, data=data, headers=headers, proxy=proxy) as res:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 899, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1325, in _create_proxy_connection
    return await self._start_tls_connection(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1105, in _start_tls_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host exhentai.org:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')]

**Comment by synodriver** [comment]
要国外机器才能上

**Comment by LumiDust** [comment]
意思是开代理也不行吗

**Comment by synodriver** [comment]
因为你的代理很有可能万人骑（

**Comment by LumiDust** [comment]
这样子，那只能试试国外服务器了（

**Comment by LumiDust** [comment]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_picsearcher\__init__.py", line 86, in get_setu
    msgs = [msg if isinstance(msg, Message) else Message(msg) async for msg in get_des(url, mod)]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_picsearcher\__init__.py", line 86, in <listcomp>
    msgs = [msg if isinstance(msg, Message) else Message(msg) async for msg in get_des(url, mod)]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_picsearcher\__init__.py", line 39, in get_des
    async for msg in get_des_ex(url):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_picsearcher\ex.py", line 99, in get_des
    image_data: List[Tuple] = await get_pic_from_url(url)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_picsearcher\ex.py", line 74, in get_pic_from_url
    async with session.post(target, data=data, headers=headers, proxy=proxy) as res:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 899, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1275, in _create_proxy_connection
    resp = await proxy_resp.start(conn)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

**Comment by LumiDust** [comment]
> Traceback (most recent call last): File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_picsearcher__init__.py", line 86, in get_setu msgs = [msg if isinstance(msg, Message) else Message(msg) async for msg in get_des(url, mod)] File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_picsearcher__init__.py", line 86, in msgs = [msg if isinstance(msg, Message) else Message(msg) async for msg in get_des(url, mod)] File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_picsearcher__init__.py", line 39, in get_des async for msg in get_des_ex(url): File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_picsearcher\ex.py", line 99, in get_des image_data: List[Tuple] = await get_pic_from_url(url) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_picsearcher\ex.py", line 74, in get_pic_from_url async with session.post(target, data=data, headers=headers, proxy=proxy) as res: File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 1141, in **aenter** self._resp = await self._coro File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 536, in _request conn = await self._connector.connect( File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 540, in connect proto = await self._create_connection(req, traces, timeout) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 899, in _create_connection _, proto = await self._create_proxy_connection(req, traces, timeout) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\connector.py", line 1275, in _create_proxy_connection resp = await proxy_resp.start(conn) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client_reqrep.py", line 899, in start message, payload = await protocol.read() # type: ignore[union-attr] File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\streams.py", line 616, in read await self._waiter aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

在修改代理为socks端口后，由题主同样报错改为此报错
![image](https://user-images.githubusercontent.com/116658416/209602170-2600dfaa-5543-42a7-a79e-fe1c7d93240e.png)
