### ISSUE TITLE
ex搜图报超时

### ISSUE THREAD

**Issue by CCYellowStar** [synodriver/nonebot_plugin_picsearcher#34]
cookie填了代理，没填，如果填了代理又会报另一个错误
没填代理报的
```
真寻七号 14:24:57
参数错误

真寻七号 14:24:57
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\aiohttp\connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 703, in sock_connect
    return await self._proactor.connect(sock, address)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 817, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 604, in finish_connect
    ov.getresult()
OSError: [WinError 121] 信号灯超时时间已到

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\zhenxunbot\myp\nonebot_plugin_picsearcher\__init__.py", line 99, in get_setu
    async for msg in limiter(get_des(url, mod), getattr(bot.config, "search_limit", None) or 2):
  File "C:\zhenxunbot\myp\nonebot_plugin_picsearcher\utils.py", line 9, in limiter
    yield await gen.asend(None)
  File "C:\zhenxunbot\myp\nonebot_plugin_picsearcher\__init__.py", line 55, in get_des
    async for msg in get_des_ex(url):
  File "C:\zhenxunbot\myp\nonebot_plugin_picsearcher\ex.py", line 99, in get_des
    image_data: List[Tuple] = await get_pic_from_url(url)
  File "C:\zhenxunbot\myp\nonebot_plugin_picsearcher\ex.py", line 74, in get_pic_from_url
    async with session.post(target, data=data, headers=headers, proxy=proxy) as res:
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\aiohttp\client.py", line 535, in _request
    conn = await self._connector.connect(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\aiohttp\connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\aiohttp\connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\aiohttp\connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host exhentai.org:443 ssl:default [信号灯超时时间已到]
```
填了代理后，好像搜啥都这样
```
06-08 14:33:52 [ERROR] nonebot | Running matcher <Matcher from myp.nonebot_plugin_picsearcher, type=message, priority=0, temp=True> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\zhenxunbot\myp\nonebot_plugin_reboot\reloader.py", line 27, in _run
    _nb_run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\nonebot\__init__.py", line 259, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "C:\zhenxunbot\myp\nonebot_plugin_picsearcher\__init__.py", line 99, in get_setu
    async for msg in limiter(get_des(url, mod), getattr(bot.config, "search_limit", None) or 2):
  File "C:\zhenxunbot\myp\nonebot_plugin_picsearcher\utils.py", line 9, in limiter
    yield await gen.asend(None)
  File "C:\zhenxunbot\myp\nonebot_plugin_picsearcher\__init__.py", line 55, in get_des
    async for msg in get_des_ex(url):
  File "C:\zhenxunbot\myp\nonebot_plugin_picsearcher\ex.py", line 99, in get_des
    image_data: List[Tuple] = await get_pic_from_url(url)
  File "C:\zhenxunbot\myp\nonebot_plugin_picsearcher\ex.py", line 74, in get_pic_from_url
    async with session.post(target, data=data, headers=headers, proxy=proxy) as res:
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\aiohttp\client.py", line 535, in _request
    conn = await self._connector.connect(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\aiohttp\connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\aiohttp\connector.py", line 905, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\aiohttp\connector.py", line 1325, in _create_proxy_connection
    return await self._start_tls_connection(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\aiohttp\connector.py", line 1126, in _start_tls_connection
    tls_proto.connection_made(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\aiohttp\base_protocol.py", line 58, in connection_made
    tcp_nodelay(tr, True)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RRUVFIbM-py3.9\lib\site-packages\aiohttp\tcp_helpers.py", line 26, in tcp_nodelay
    sock = transport.get_extra_info("socket")
AttributeError: 'NoneType' object has no attribute 'get_extra_info'
```

**Comment by synodriver** [comment]
是http代理吗

**Comment by CCYellowStar** [comment]
clash的

**Comment by synodriver** [comment]
确认了ip的连通性吗？ex有时候会banip的

**Comment by CCYellowStar** [comment]
那个真寻机器人他有一个全局代理配置在，这个可以和那个代理配置共存的吧

**Comment by synodriver** [comment]
emmm……这个只要http代理……开了全局的不知道会出什么莫名其妙的问题（

**Comment by forchannot** [comment]
> emmm……这个只要http代理……开了全局的不知道会出什么莫名其妙的问题（

请问下设置了http代理，但是并没有设置cookie，按理说应该会去eh搜索呀，但是报错Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot_plugin_picsearcher\__init__.py", line 86, in get_setu
    msgs = [msg if isinstance(msg, Message) else Message(msg) async for msg in get_des(url, mod)]
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot_plugin_picsearcher\__init__.py", line 86, in <listcomp>
    msgs = [msg if isinstance(msg, Message) else Message(msg) async for msg in get_des(url, mod)]
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot_plugin_picsearcher\__init__.py", line 39, in get_des
    async for msg in get_des_ex(url):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot_plugin_picsearcher\ex.py", line 99, in get_des
    image_data: List[Tuple] = await get_pic_from_url(url)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot_plugin_picsearcher\ex.py", line 74, in get_pic_from_url
    async with session.post(target, data=data, headers=headers, proxy=proxy) as res:
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\aiohttp\connector.py", line 899, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\aiohttp\connector.py", line 1275, in _create_proxy_connection
    resp = await proxy_resp.start(conn)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\aiohttp\client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\aiohttp\streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [WinError 64] 指定的网络名不再可用。
