### ISSUE TITLE
搜图后出现expected string or bytes-like object报错

### ISSUE THREAD

**Issue by avadiana** [synodriver/nonebot_plugin_picsearcher#36]
大佬，我的配置是这个![image](https://user-images.githubusercontent.com/88984346/185735099-58cdb0c7-48df-4f79-9430-39d1e46c2cac.png)，搜图后无论是哪个网站，都会显示如下报错
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 639, in simple_run
    await handler(
  File "/usr/local/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/usr/local/lib/python3.9/site-packages/nonebot_plugin_picsearcher/__init__.py", line 85, in get_setu
    msgs: Message = sum(
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/onebot/v11/message.py", line 284, in __radd__
    return super(Message, self).__radd__(
  File "/usr/local/lib/python3.9/site-packages/nonebot/internal/adapter/message.py", line 178, in __radd__
    result = self.__class__(other)
  File "/usr/local/lib/python3.9/site-packages/nonebot/internal/adapter/message.py", line 117, in __init__
    self.extend(self._construct(message))  # pragma: no cover
  File "/usr/local/lib/python3.9/site-packages/nonebot/internal/adapter/message.py", line 311, in extend
    for segment in obj:
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/onebot/v11/message.py", line 313, in _construct
    for type_, data in _iter_message(msg):
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/onebot/v11/message.py", line 301, in _iter_message
    for cqcode in re.finditer(
  File "/usr/local/lib/python3.9/re.py", line 248, in finditer
    return _compile(pattern, flags).finditer(string)
TypeError: expected string or bytes-like object
大佬能帮忙看看是什么原因吗

**Comment by synodriver** [comment]
这个似乎不是我的问题

**Comment by synodriver** [comment]
pip install nonebot-plugin-picsearcher==0.1.9.dev1  治标先

**Comment by synodriver** [comment]
pip install -U  nonebot-plugin-picsearcher 彻底修好了

**Comment by synodriver** [comment]
sum函数和更新后的nb发生了奇妙的反应，导致一个0被塞进了```re.compile```，已经更新了，顺便优化了性能
