### ISSUE TITLE
私聊可以正常使用，群聊使用就会报错

### ISSUE THREAD

**Issue by if-u-can** [synodriver/nonebot_plugin_picsearcher#37]
只有群聊使用会报这个错误
08-29 18:41:14 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_picsearcher, type=message, priority=0, temp=True> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\python\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "D:\python\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\python\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "D:\python\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\python\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "D:\python\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "D:\python\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "D:\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\python\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "D:\python\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\python\lib\site-packages\nonebot\internal\matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\python\lib\site-packages\nonebot\internal\matcher.py", line 639, in simple_run
    await handler(
  File "D:\python\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "D:\python\lib\site-packages\nonebot_plugin_picsearcher\__init__.py", line 85, in get_setu
    msgs: Message = sum(
  File "D:\python\lib\site-packages\nonebot\adapters\onebot\v11\message.py", line 284, in __radd__
    return super(Message, self).__radd__(
  File "D:\python\lib\site-packages\nonebot\internal\adapter\message.py", line 178, in __radd__
    result = self.__class__(other)
  File "D:\python\lib\site-packages\nonebot\internal\adapter\message.py", line 117, in __init__
    self.extend(self._construct(message))  # pragma: no cover
  File "D:\python\lib\site-packages\nonebot\internal\adapter\message.py", line 311, in extend
    for segment in obj:
  File "D:\python\lib\site-packages\nonebot\adapters\onebot\v11\message.py", line 313, in _construct
    for type_, data in _iter_message(msg):
  File "D:\python\lib\site-packages\nonebot\adapters\onebot\v11\message.py", line 301, in _iter_message
    for cqcode in re.finditer(
  File "D:\python\lib\re.py", line 247, in finditer
    return _compile(pattern, flags).finditer(string)
TypeError: expected string or bytes-like object

**Comment by synodriver** [comment]
我根本就没用到on_regex，怎么会报re的错....你的nonebot版本和python版本？

**Comment by tomorinao-www** [comment]
我遇到了同样的问题，群聊中使用就会报如上错误

**Comment by chrd123w** [comment]
@synodriver 同样是在群聊中遇到的问题
10-15 14:31:20 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
10-15 14:31:25 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_pi
csearcher) running complete
10-15 14:31:25 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_
plugin_picsearcher) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\.conda\envs\Bot\lib\runpy.py", line 196, in _run_
module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\.conda\envs\Bot\lib\runpy.py", line 86, in _run_c
ode
    exec(code, run_globals)
  File "C:\Users\Administrator\.conda\envs\Bot\Scripts\nb.exe\__main__.py", line
 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\.conda\envs\Bot\lib\site-packages\click\core.py",
 line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\.conda\envs\Bot\lib\site-packages\click\core.py",
 line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\.conda\envs\Bot\lib\site-packages\click\core.py",
 line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\.conda\envs\Bot\lib\site-packages\click\core.py",
 line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\.conda\envs\Bot\lib\site-packages\click\core.py",
 line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\.conda\envs\Bot\lib\site-packages\nb_cli\commands
\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\.conda\envs\Bot\lib\site-packages\nb_cli\handlers
\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\Administrator\.conda\envs\Bot\lib\site-packages\nonebot\__init_
_.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\.conda\envs\Bot\lib\site-packages\nonebot\drivers
\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\Administrator\.conda\envs\Bot\lib\site-packages\uvicorn\main.py
", line 576, in run
    server.run()
  File "C:\Users\Administrator\.conda\envs\Bot\lib\site-packages\uvicorn\server.
py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\.conda\envs\Bot\lib\asyncio\runners.py", line 44,
 in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\.conda\envs\Bot\lib\asyncio\base_events.py", line
 628, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\.conda\envs\Bot\lib\asyncio\windows_events.py", l
ine 316, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\.conda\envs\Bot\lib\asyncio\base_events.py", line
 595, in run_forever
    self._run_once()
  File "C:\Users\Administrator\.conda\envs\Bot\lib\asyncio\base_events.py", line
 1881, in _run_once
    handle._run()
  File "C:\Users\Administrator\.conda\envs\Bot\lib\asyncio\events.py", line 80,
in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\.conda\envs\Bot\lib\site-packages\nonebot\message
.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\.conda\envs\Bot\lib\site-packages\nonebot\message
.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\.conda\envs\Bot\lib\site-packages\nonebot\interna
l\matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\.conda\envs\Bot\lib\site-packages\nonebot\interna
l\matcher.py", line 688, in simple_run
    await handler(
  File "C:\Users\Administrator\.conda\envs\Bot\lib\site-packages\nonebot\depende
ncies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\.conda\envs\Bot\lib\site-packages\nonebot_plugin_
picsearcher\__init__.py", line 85, in get_setu
    msgs: Message = sum(
  File "C:\Users\Administrator\.conda\envs\Bot\lib\site-packages\nonebot\adapter
s\onebot\v11\message.py", line 284, in __radd__
    return super(Message, self).__radd__(
  File "C:\Users\Administrator\.conda\envs\Bot\lib\site-packages\nonebot\interna
l\adapter\message.py", line 178, in __radd__
    result = self.__class__(other)
  File "C:\Users\Administrator\.conda\envs\Bot\lib\site-packages\nonebot\interna
l\adapter\message.py", line 117, in __init__
    self.extend(self._construct(message))  # pragma: no cover
  File "C:\Users\Administrator\.conda\envs\Bot\lib\site-packages\nonebot\interna
l\adapter\message.py", line 311, in extend
    for segment in obj:
  File "C:\Users\Administrator\.conda\envs\Bot\lib\site-packages\nonebot\adapter
s\onebot\v11\message.py", line 313, in _construct
    for type_, data in _iter_message(msg):
  File "C:\Users\Administrator\.conda\envs\Bot\lib\site-packages\nonebot\adapter
s\onebot\v11\message.py", line 301, in _iter_message
    for cqcode in re.finditer(
  File "C:\Users\Administrator\.conda\envs\Bot\lib\re.py", line 247, in finditer

    return _compile(pattern, flags).finditer(string)
TypeError: expected string or bytes-like object

**Comment by synodriver** [comment]
初步定位https://github.com/synodriver/nonebot_plugin_picsearcher/blob/beta1/nonebot_plugin_picsearcher/__init__.py#L85-L86 ，应该是nonebot更新了什么

**Comment by synodriver** [comment]
要是能赞助一个debug的号就好了（我号被封光了）

**Comment by synodriver** [comment]
这里 https://github.com/nonebot/nonebot2/blob/master/nonebot/internal/adapter/message.py#L117
打个断点看看

**Comment by synodriver** [comment]
今天我薅个号debug看看（

**Comment by synodriver** [comment]
pip install -U nonebot-plugin-picsearcher 彻底修好了

**Comment by 0xAmad3us** [comment]
> pip install -U nonebot-plugin-picsearcher 彻底修好了

又出了这个问题，是防风控那个打包成记录转发的锅，把防风控关掉就没有这个问题了
