### ISSUE TITLE
项目支持的python版本是？

### ISSUE THREAD

**Issue by fatinghenji** [synodriver/nonebot_plugin_picsearcher#39]
目前使用的python版本是3.10.7，出现代理错误，请问支持的版本是？
报错代码如下：
```python
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/nonebot_plugin_picsearcher/__init__.py", line 86, in get_setu
    [msg if isinstance(msg, Message) else Message(msg) async for msg in get_des(url, mod)])
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/nonebot_plugin_picsearcher/__init__.py", line 86, in <listcomp>
    [msg if isinstance(msg, Message) else Message(msg) async for msg in get_des(url, mod)])
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/nonebot_plugin_picsearcher/__init__.py", line 47, in get_des
    async for msg in get_des_asc(url):
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/nonebot_plugin_picsearcher/ascii2d.py", line 39, in get_des
    image_data: List[Tuple] = await get_pic_from_url(url)
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/nonebot_plugin_picsearcher/ascii2d.py", line 33, in get_pic_from_url
    async with session.get(real_url, proxy=proxy) as resp:
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/aiohttp/connector.py", line 905, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/aiohttp/connector.py", line 1221, in _create_proxy_connection
    proxy_req = ClientRequest(
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 305, in __init__
    self.update_host(url)
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 366, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: #%20type:%20str%20e.g.%20PROXY=http://127.0.0.1:8889
```

**Comment by fatinghenji** [comment]
似乎在这里有提到解决办法，但是我不会编程。
[aiohttp.client_exceptions.InvalidURL: %E5%9B%BE%E7%89%87%E9%93%BE%E6%8E%A5](https://blog.csdn.net/h1751541643/article/details/114578552)

**Comment by synodriver** [comment]
你的配置文件怎么写的
