### ISSUE TITLE
报错，参数错误

### ISSUE THREAD

**Issue by zerobeyondlogic** [synodriver/nonebot_plugin_picsearcher#41]
09-20 21:38:41 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_picsearcher, type=message, priority=0, temp=True>
/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/aiohttp/connector.py:905: RuntimeWarning: An HTTPS request is being sent through an HTTPS proxy. This support for TLS in TLS is known to be disabled in the stdlib asyncio. This is why you'll probably see an error in the log below.

It is possible to enable it via monkeypatching under Python 3.7 or higher. For more details, see:
* https://bugs.python.org/issue37179
* https://github.com/python/cpython/pull/28073

You can temporarily patch this as follows:
* https://docs.aiohttp.org/en/stable/client_advanced.html#proxy-support
* https://github.com/aio-libs/aiohttp/discussions/6044

  _, proto = await self._create_proxy_connection(req, traces, timeout)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
![image](https://user-images.githubusercontent.com/53165745/191273375-62fb62cf-6538-440a-9ad9-2cc9ccc9dfa9.png)

在提示中给出了一些“解决方案”，看起来要修改调用了aiohttp的某些语句，但不知具体如何应用。

我是用的代理是v2ray
proxy设置为socks5://127.0.0.1:10808

**Comment by zerobeyondlogic** [comment]
如果暂时禁用proxy，
报错是timeout,看来无法直连
![image](https://user-images.githubusercontent.com/53165745/191275258-8055f28b-7d76-47fb-9e3a-145b0bdce80b.png)
09-20 21:47:33 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_picsearcher, type=message, priority=0, temp=True> failed.
Traceback (most recent call last):
  File "/home/beyond/qqbot/bot/bot.py", line 37, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
  File "/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/uvicorn/main.py", line 576, in run
    server.run()
  File "/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/nonebot/internal/matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/nonebot/internal/matcher.py", line 639, in simple_run
    await handler(
  File "/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/nonebot_plugin_picsearcher/__init__.py", line 83, in get_setu
    await bot.send(event=event, message=msg)
  File "/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/bot.py", line 220, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/bot.py", line 175, in send
    return await bot.send_msg(**params)
  File "/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 117, in call_api
    raise exception
  File "/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/home/beyond/qqbot/qqbotpy/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 136, in _call_api
    raise NetworkError(f"WebSocket call api {api} timeout") from None
nonebot.adapters.onebot.v11.exception.NetworkError: <NetWorkError message=WebSocket call api send_msg timeout>

**Comment by synodriver** [comment]
似乎是上游aiohttp的锅

**Comment by synodriver** [comment]
似乎是链接断开了 看看gocq的log

**Comment by deacfb** [comment]
这个不用管，有时候就算不是http代理也会报错，这个不影响运行
