### ISSUE TITLE
下载picsearcher后无法处理图片

### ISSUE THREAD

**Issue by z9p1** [synodriver/nonebot_plugin_picsearcher#50]
问题：搜索图片后控制台可以抓到”搜“但无图片返回

排查：当启动该插件时周期性提示：
Task exception was never retrieved
future: <Task finished name='Task-84' coro=<Bot.handle_event() done, defined at C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\onebot\v11\bot.py:186> exception=TypeError("'<' not supported between instances of 'str' and 'int'")>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 193, in handle_event
    await handle_event(self, event)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 288, in handle_event
    for priority in sorted(matchers.keys()):
TypeError: '<' not supported between instances of 'str' and 'int'

环境操作如下：已pip install Brotli ，pip install nonebot-plugin-picsearcher 设置配置项，未在 nonebot2 项目中设置 load_plugin()（设置后会提示已存在不需要）

**Comment by synodriver** [comment]
你的python版本，nonebot版本和这个插件的版本？
