### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'SendGroupForwardMsgResult'

### ISSUE THREAD

**Issue by Tanka-Az** [synodriver/nonebot_plugin_picsearcher#60]
>[PyBot][02:54:28.725][ERROR] [message]Running Matcher(type='message', module=non
ebot_plugin_picsearcher) failed.
Traceback (most recent call last):
  File "D:\server\Yunzai\plugins\py-plugin\main.py", line 13, in <module>
    nonebot.run(root)
  File "D:\server\Yunzai\plugins\py-plugin\nonebot\__init__.py", line 56, in run
    _driver.run([str(x) for x in _driver.config.plugins])
  File "D:\server\Yunzai\plugins\py-plugin\nonebot\drivers.py", line 48, in run
    loop.run_until_complete(self.serve(plugins))
  File "C:\Users\tanka\AppData\Local\Programs\Python\Python310\lib\asyncio\base_
events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\tanka\AppData\Local\Programs\Python\Python310\lib\asyncio\windo
ws_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\tanka\AppData\Local\Programs\Python\Python310\lib\asyncio\base_
events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\tanka\AppData\Local\Programs\Python\Python310\lib\asyncio\base_
events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\tanka\AppData\Local\Programs\Python\Python310\lib\asyncio\event
s.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\server\Yunzai\plugins\py-plugin\nonebot\message.py", line 130, in _ch
eck_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "D:\server\Yunzai\plugins\py-plugin\nonebot\message.py", line 182, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\server\Yunzai\plugins\py-plugin\nonebot\internal\matcher.py", line 721, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\server\Yunzai\plugins\py-plugin\nonebot\internal\matcher.py", line 696, in simple_run
    await handler(
  File "D:\server\Yunzai\plugins\py-plugin\nonebot\dependencies\__init__.py", line 83, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\tanka\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-0I-3EAGL-py3.10\lib\site-packages\nonebot_plugin_picsearcher\__init__.py", lin
e 89, in get_setu
    await bot.send_group_forward_msg(group_id=event.group_id,
  File "D:\server\Yunzai\plugins\py-plugin\nonebot\adapters\onebot\v11\bot.py", line 525, in send_group_forward_msg
    result: GRPCSendGroupForwardMsgResult = (await self.result_map.get(request_id)).SendGroupForwardMsgResult
AttributeError: 'NoneType' object has no attribute 'SendGroupForwardMsgResult'

所有搜索方式都会这样

**Comment by synodriver** [comment]
用的什么adapter？Nonebot版本？似乎是这个bot做了一些monkeypatch，我自己的没出现这样的bug
