### ISSUE TITLE
建议添加过滤R18内容的参数

### ISSUE THREAD

**Issue by jiajiu123** [synodriver/nonebot_plugin_picsearcher#7]

**Comment by synodriver** [comment]
~~R18不挺好吗~~

**Comment by jiajiu123** [comment]
怕号没（）

**Comment by synodriver** [comment]
我康康……其实网站也没说这个是不是r18，如果一定要鉴黄的话，这有个训练好部署好的[神经网络api](https://github.com/synodriver/unit_strange_code/actions) ，用uvicorn启动就是

**Comment by synodriver** [comment]
> 我康康……其实网站也没说这个是不是r18，如果一定要鉴黄的话，这有个训练好部署好的[神经网络api](https://github.com/synodriver/unit_strange_code/actions) ，用uvicorn启动就是

需要TensorFlow全家桶

**Comment by synodriver** [comment]
我有了个好办法https://github.com/synodriver/nonebot_plugin_picsearcher/issues/8

**Comment by citydirector** [comment]
如果得到图源的pixiv的话，倒是可以识别图片标签有没有R-18

**Comment by snakeuncle2** [comment]
大佬你好，我是纯小白一个，试着自己搭了一个bot和您的插件
dev的设置如下HOST=127.0.0.1
PORT=8080  
SUPERUSERS=["512019302", "778688058"] 
NICKNAME=["snake", "bot"]  # 配置机器人的昵称
COMMAND_START=["/", ""]  # 配置命令起始字符
COMMAND_SEP=["."]  # 配置命令分割字符

# Custom Configs
CUSTOM_CONFIG1="config in env file"
CUSTOM_CONFIG2=  # 留空则从系统环境变量读取，如不存在则为空字符串
EX_COOKIE=XXXXX
PROXY=http://127.0.0.1:4780  # type: str e.g. PROXY=http://127.0.0.1:8080
SEARCH_LIMIT=2  # 搜索限制 防刷屏
RISK_CONTROL=true # 风控模式 启动后会使用合并转发 只有gocq有实现
RECORD_PRIORITY=99 # 记录上一张图片matcher的优先级，与 上一张 命令有关

然后是错误参数
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1119, in _create_connection_transport
    await waiter
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 397, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 534, in send
    self._register_with_iocp(conn)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 723, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 87] 参数错误。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_picsearcher\__init__.py", line 83, in get_setu
    [msg if isinstance(msg, Message) else Message(msg) async for msg in get_des(url, mod)])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_picsearcher\__init__.py", line 83, in <listcomp>
    [msg if isinstance(msg, Message) else Message(msg) async for msg in get_des(url, mod)])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_picsearcher\__init__.py", line 47, in get_des
    async for msg in get_des_sau(url):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_picsearcher\saucenao.py", line 84, in get_des
    image_data: List[Tuple] = await get_pic_from_url(url)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_picsearcher\saucenao.py", line 77, in get_pic_from_url
    async with session.post("https://saucenao.com/search.php", data=data, headers=header, proxy=proxy) as res:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 520, in _request
    conn = await self._connector.connect(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 890, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1139, in _create_proxy_connection
    transport, proto = await self._wrap_create_connection(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host saucenao.com:443 ssl:default [参数错误。]


我按照您的步骤和上网查找了问题，发现不知道如何解决，麻烦请您帮看一下，谢谢
